apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: prubita-live-tls
spec:
  secretName: prubita-live
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: prubita.live
  dnsNames:
    - prubita.live
    - www.prubita.live
